- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.2.2
  hooks:
    - id: nbqa-black
    - id: nbqa-pyupgrade
      args: [--py36-plus]
    - id: nbqa-isort
    - id: mdformat
      args: [--nbqa-md, --nbqa-diff]
